#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
i, j = 1, 1
soma = 0

while i <= 4000000:
    if i % 2 == 0:
        soma += i
    i, j = i + j, i
    
print(soma)